// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: rolodex.proto

package rolodexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolodexService_AddRecord_FullMethodName     = "/rolodex.RolodexService/AddRecord"
	RolodexService_RemoveRecord_FullMethodName  = "/rolodex.RolodexService/RemoveRecord"
	RolodexService_ListRecords_FullMethodName   = "/rolodex.RolodexService/ListRecords"
	RolodexService_SetForwarders_FullMethodName = "/rolodex.RolodexService/SetForwarders"
	RolodexService_SetRblConfig_FullMethodName  = "/rolodex.RolodexService/SetRblConfig"
	RolodexService_GetRblConfig_FullMethodName  = "/rolodex.RolodexService/GetRblConfig"
	RolodexService_FlushCache_FullMethodName    = "/rolodex.RolodexService/FlushCache"
)

// RolodexServiceClient is the client API for RolodexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RolodexService provides the gRPC management interface for rolodex.
//
// All methods accept an auth_token field for shared-secret authentication.
// When connecting over a unix socket, the auth_token is ignored.
type RolodexServiceClient interface {
	// AddRecord adds a DNS record to the local database.
	// Path: /rolodex.RolodexService/AddRecord
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	// RemoveRecord removes DNS record(s) from the local database.
	// Path: /rolodex.RolodexService/RemoveRecord
	RemoveRecord(ctx context.Context, in *RemoveRecordRequest, opts ...grpc.CallOption) (*RemoveRecordResponse, error)
	// ListRecords queries the local DNS database with optional filters.
	// Path: /rolodex.RolodexService/ListRecords
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error)
	// SetForwarders configures the upstream DNS forwarders.
	// Path: /rolodex.RolodexService/SetForwarders
	SetForwarders(ctx context.Context, in *SetForwarderRequest, opts ...grpc.CallOption) (*SetForwarderResponse, error)
	// SetRblConfig configures RBL (Realtime Blackhole List) settings.
	// Path: /rolodex.RolodexService/SetRblConfig
	SetRblConfig(ctx context.Context, in *SetRblConfigRequest, opts ...grpc.CallOption) (*SetRblConfigResponse, error)
	// GetRblConfig retrieves the current RBL configuration.
	// Path: /rolodex.RolodexService/GetRblConfig
	GetRblConfig(ctx context.Context, in *GetRblConfigRequest, opts ...grpc.CallOption) (*GetRblConfigResponse, error)
	// FlushCache clears DNS and RBL caches.
	// Path: /rolodex.RolodexService/FlushCache
	FlushCache(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error)
}

type rolodexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolodexServiceClient(cc grpc.ClientConnInterface) RolodexServiceClient {
	return &rolodexServiceClient{cc}
}

func (c *rolodexServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, RolodexService_AddRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) RemoveRecord(ctx context.Context, in *RemoveRecordRequest, opts ...grpc.CallOption) (*RemoveRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRecordResponse)
	err := c.cc.Invoke(ctx, RolodexService_RemoveRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecordsResponse)
	err := c.cc.Invoke(ctx, RolodexService_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) SetForwarders(ctx context.Context, in *SetForwarderRequest, opts ...grpc.CallOption) (*SetForwarderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetForwarderResponse)
	err := c.cc.Invoke(ctx, RolodexService_SetForwarders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) SetRblConfig(ctx context.Context, in *SetRblConfigRequest, opts ...grpc.CallOption) (*SetRblConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRblConfigResponse)
	err := c.cc.Invoke(ctx, RolodexService_SetRblConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) GetRblConfig(ctx context.Context, in *GetRblConfigRequest, opts ...grpc.CallOption) (*GetRblConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRblConfigResponse)
	err := c.cc.Invoke(ctx, RolodexService_GetRblConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolodexServiceClient) FlushCache(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushCacheResponse)
	err := c.cc.Invoke(ctx, RolodexService_FlushCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolodexServiceServer is the server API for RolodexService service.
// All implementations must embed UnimplementedRolodexServiceServer
// for forward compatibility.
//
// RolodexService provides the gRPC management interface for rolodex.
//
// All methods accept an auth_token field for shared-secret authentication.
// When connecting over a unix socket, the auth_token is ignored.
type RolodexServiceServer interface {
	// AddRecord adds a DNS record to the local database.
	// Path: /rolodex.RolodexService/AddRecord
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	// RemoveRecord removes DNS record(s) from the local database.
	// Path: /rolodex.RolodexService/RemoveRecord
	RemoveRecord(context.Context, *RemoveRecordRequest) (*RemoveRecordResponse, error)
	// ListRecords queries the local DNS database with optional filters.
	// Path: /rolodex.RolodexService/ListRecords
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error)
	// SetForwarders configures the upstream DNS forwarders.
	// Path: /rolodex.RolodexService/SetForwarders
	SetForwarders(context.Context, *SetForwarderRequest) (*SetForwarderResponse, error)
	// SetRblConfig configures RBL (Realtime Blackhole List) settings.
	// Path: /rolodex.RolodexService/SetRblConfig
	SetRblConfig(context.Context, *SetRblConfigRequest) (*SetRblConfigResponse, error)
	// GetRblConfig retrieves the current RBL configuration.
	// Path: /rolodex.RolodexService/GetRblConfig
	GetRblConfig(context.Context, *GetRblConfigRequest) (*GetRblConfigResponse, error)
	// FlushCache clears DNS and RBL caches.
	// Path: /rolodex.RolodexService/FlushCache
	FlushCache(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error)
	mustEmbedUnimplementedRolodexServiceServer()
}

// UnimplementedRolodexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolodexServiceServer struct{}

func (UnimplementedRolodexServiceServer) AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedRolodexServiceServer) RemoveRecord(context.Context, *RemoveRecordRequest) (*RemoveRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRecord not implemented")
}
func (UnimplementedRolodexServiceServer) ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedRolodexServiceServer) SetForwarders(context.Context, *SetForwarderRequest) (*SetForwarderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetForwarders not implemented")
}
func (UnimplementedRolodexServiceServer) SetRblConfig(context.Context, *SetRblConfigRequest) (*SetRblConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRblConfig not implemented")
}
func (UnimplementedRolodexServiceServer) GetRblConfig(context.Context, *GetRblConfigRequest) (*GetRblConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRblConfig not implemented")
}
func (UnimplementedRolodexServiceServer) FlushCache(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushCache not implemented")
}
func (UnimplementedRolodexServiceServer) mustEmbedUnimplementedRolodexServiceServer() {}
func (UnimplementedRolodexServiceServer) testEmbeddedByValue()                        {}

// UnsafeRolodexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolodexServiceServer will
// result in compilation errors.
type UnsafeRolodexServiceServer interface {
	mustEmbedUnimplementedRolodexServiceServer()
}

func RegisterRolodexServiceServer(s grpc.ServiceRegistrar, srv RolodexServiceServer) {
	// If the following call panics, it indicates UnimplementedRolodexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolodexService_ServiceDesc, srv)
}

func _RolodexService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_RemoveRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).RemoveRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_RemoveRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).RemoveRecord(ctx, req.(*RemoveRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_SetForwarders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetForwarderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).SetForwarders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_SetForwarders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).SetForwarders(ctx, req.(*SetForwarderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_SetRblConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRblConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).SetRblConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_SetRblConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).SetRblConfig(ctx, req.(*SetRblConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_GetRblConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRblConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).GetRblConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_GetRblConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).GetRblConfig(ctx, req.(*GetRblConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolodexService_FlushCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolodexServiceServer).FlushCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolodexService_FlushCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolodexServiceServer).FlushCache(ctx, req.(*FlushCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolodexService_ServiceDesc is the grpc.ServiceDesc for RolodexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolodexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rolodex.RolodexService",
	HandlerType: (*RolodexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _RolodexService_AddRecord_Handler,
		},
		{
			MethodName: "RemoveRecord",
			Handler:    _RolodexService_RemoveRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _RolodexService_ListRecords_Handler,
		},
		{
			MethodName: "SetForwarders",
			Handler:    _RolodexService_SetForwarders_Handler,
		},
		{
			MethodName: "SetRblConfig",
			Handler:    _RolodexService_SetRblConfig_Handler,
		},
		{
			MethodName: "GetRblConfig",
			Handler:    _RolodexService_GetRblConfig_Handler,
		},
		{
			MethodName: "FlushCache",
			Handler:    _RolodexService_FlushCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rolodex.proto",
}
