// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rolodex.proto

package rolodexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordType enumerates the supported DNS record types.
type RecordType int32

const (
	// A record - IPv4 address mapping
	RecordType_A RecordType = 0
	// AAAA record - IPv6 address mapping
	RecordType_AAAA RecordType = 1
	// CNAME record - canonical name alias
	RecordType_CNAME RecordType = 2
	// MX record - mail exchange
	RecordType_MX RecordType = 3
	// TXT record - text record
	RecordType_TXT RecordType = 4
	// NS record - name server
	RecordType_NS RecordType = 5
	// SOA record - start of authority
	RecordType_SOA RecordType = 6
	// SRV record - service locator
	RecordType_SRV RecordType = 7
	// PTR record - pointer for reverse DNS
	RecordType_PTR RecordType = 8
)

// Enum value maps for RecordType.
var (
	RecordType_name = map[int32]string{
		0: "A",
		1: "AAAA",
		2: "CNAME",
		3: "MX",
		4: "TXT",
		5: "NS",
		6: "SOA",
		7: "SRV",
		8: "PTR",
	}
	RecordType_value = map[string]int32{
		"A":     0,
		"AAAA":  1,
		"CNAME": 2,
		"MX":    3,
		"TXT":   4,
		"NS":    5,
		"SOA":   6,
		"SRV":   7,
		"PTR":   8,
	}
)

func (x RecordType) Enum() *RecordType {
	p := new(RecordType)
	*p = x
	return p
}

func (x RecordType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordType) Descriptor() protoreflect.EnumDescriptor {
	return file_rolodex_proto_enumTypes[0].Descriptor()
}

func (RecordType) Type() protoreflect.EnumType {
	return &file_rolodex_proto_enumTypes[0]
}

func (x RecordType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordType.Descriptor instead.
func (RecordType) EnumDescriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{0}
}

// DnsRecord represents a single DNS record in the database.
type DnsRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified domain name (e.g. "example.com.")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The type of DNS record
	RecordType RecordType `protobuf:"varint,2,opt,name=record_type,json=recordType,proto3,enum=rolodex.RecordType" json:"record_type,omitempty"`
	// The record data (e.g. IP address, hostname, etc.)
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Time-to-live in seconds (default: 300)
	Ttl uint32 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Priority for MX and SRV records (ignored for other types)
	Priority      uint32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecord) Reset() {
	*x = DnsRecord{}
	mi := &file_rolodex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecord) ProtoMessage() {}

func (x *DnsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecord.ProtoReflect.Descriptor instead.
func (*DnsRecord) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{0}
}

func (x *DnsRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DnsRecord) GetRecordType() RecordType {
	if x != nil {
		return x.RecordType
	}
	return RecordType_A
}

func (x *DnsRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DnsRecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DnsRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// AddRecordRequest adds a new DNS record to the local database.
type AddRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record to add
	Record *DnsRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// Shared secret for authentication (ignored over unix socket)
	AuthToken     string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordRequest) Reset() {
	*x = AddRecordRequest{}
	mi := &file_rolodex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordRequest) ProtoMessage() {}

func (x *AddRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordRequest.ProtoReflect.Descriptor instead.
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{1}
}

func (x *AddRecordRequest) GetRecord() *DnsRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *AddRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// AddRecordResponse is returned after adding a record.
type AddRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success is false
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecordResponse) Reset() {
	*x = AddRecordResponse{}
	mi := &file_rolodex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecordResponse) ProtoMessage() {}

func (x *AddRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecordResponse.ProtoReflect.Descriptor instead.
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{2}
}

func (x *AddRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveRecordRequest removes a DNS record from the local database.
type RemoveRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified domain name to remove records for
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional: if set, only remove records of this type. If unset, removes all records for the name.
	RecordType RecordType `protobuf:"varint,2,opt,name=record_type,json=recordType,proto3,enum=rolodex.RecordType" json:"record_type,omitempty"`
	// Optional: if set, only remove the record with this exact value
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Shared secret for authentication
	AuthToken     string `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecordRequest) Reset() {
	*x = RemoveRecordRequest{}
	mi := &file_rolodex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecordRequest) ProtoMessage() {}

func (x *RemoveRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecordRequest.ProtoReflect.Descriptor instead.
func (*RemoveRecordRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveRecordRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveRecordRequest) GetRecordType() RecordType {
	if x != nil {
		return x.RecordType
	}
	return RecordType_A
}

func (x *RemoveRecordRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RemoveRecordRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// RemoveRecordResponse is returned after removing records.
type RemoveRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Number of records removed
	RemovedCount uint32 `protobuf:"varint,2,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	// Error message if success is false
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecordResponse) Reset() {
	*x = RemoveRecordResponse{}
	mi := &file_rolodex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecordResponse) ProtoMessage() {}

func (x *RemoveRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecordResponse.ProtoReflect.Descriptor instead.
func (*RemoveRecordResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveRecordResponse) GetRemovedCount() uint32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

func (x *RemoveRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListRecordsRequest queries the local DNS database.
type ListRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by domain name (supports wildcard prefix "*.")
	NameFilter string `protobuf:"bytes,1,opt,name=name_filter,json=nameFilter,proto3" json:"name_filter,omitempty"`
	// Optional: filter by record type
	RecordTypeFilter RecordType `protobuf:"varint,2,opt,name=record_type_filter,json=recordTypeFilter,proto3,enum=rolodex.RecordType" json:"record_type_filter,omitempty"`
	// Whether to apply the record_type_filter
	FilterByType bool `protobuf:"varint,3,opt,name=filter_by_type,json=filterByType,proto3" json:"filter_by_type,omitempty"`
	// Shared secret for authentication
	AuthToken     string `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_rolodex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{5}
}

func (x *ListRecordsRequest) GetNameFilter() string {
	if x != nil {
		return x.NameFilter
	}
	return ""
}

func (x *ListRecordsRequest) GetRecordTypeFilter() RecordType {
	if x != nil {
		return x.RecordTypeFilter
	}
	return RecordType_A
}

func (x *ListRecordsRequest) GetFilterByType() bool {
	if x != nil {
		return x.FilterByType
	}
	return false
}

func (x *ListRecordsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// ListRecordsResponse contains matching DNS records.
type ListRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching records
	Records       []*DnsRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_rolodex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{6}
}

func (x *ListRecordsResponse) GetRecords() []*DnsRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// SetForwarderRequest configures upstream DNS forwarders.
type SetForwarderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of upstream DNS server addresses (e.g. "8.8.8.8:53")
	Forwarders []string `protobuf:"bytes,1,rep,name=forwarders,proto3" json:"forwarders,omitempty"`
	// Shared secret for authentication
	AuthToken     string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetForwarderRequest) Reset() {
	*x = SetForwarderRequest{}
	mi := &file_rolodex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetForwarderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetForwarderRequest) ProtoMessage() {}

func (x *SetForwarderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetForwarderRequest.ProtoReflect.Descriptor instead.
func (*SetForwarderRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{7}
}

func (x *SetForwarderRequest) GetForwarders() []string {
	if x != nil {
		return x.Forwarders
	}
	return nil
}

func (x *SetForwarderRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// SetForwarderResponse is returned after setting forwarders.
type SetForwarderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the operation succeeded
	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetForwarderResponse) Reset() {
	*x = SetForwarderResponse{}
	mi := &file_rolodex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetForwarderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetForwarderResponse) ProtoMessage() {}

func (x *SetForwarderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetForwarderResponse.ProtoReflect.Descriptor instead.
func (*SetForwarderResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{8}
}

func (x *SetForwarderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetForwarderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RblConfig configures a single RBL provider.
type RblConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RBL zone to query (e.g. "zen.spamhaus.org")
	Zone string `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	// Whether this RBL is enabled (default: true when added)
	Enabled       bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblConfig) Reset() {
	*x = RblConfig{}
	mi := &file_rolodex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblConfig) ProtoMessage() {}

func (x *RblConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblConfig.ProtoReflect.Descriptor instead.
func (*RblConfig) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{9}
}

func (x *RblConfig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *RblConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SetRblConfigRequest configures RBL providers.
type SetRblConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of RBL providers to use
	Providers []*RblConfig `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	// Whether RBL checking is globally enabled
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Shared secret for authentication
	AuthToken     string `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRblConfigRequest) Reset() {
	*x = SetRblConfigRequest{}
	mi := &file_rolodex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRblConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRblConfigRequest) ProtoMessage() {}

func (x *SetRblConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRblConfigRequest.ProtoReflect.Descriptor instead.
func (*SetRblConfigRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{10}
}

func (x *SetRblConfigRequest) GetProviders() []*RblConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *SetRblConfigRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetRblConfigRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// SetRblConfigResponse is returned after configuring RBL.
type SetRblConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRblConfigResponse) Reset() {
	*x = SetRblConfigResponse{}
	mi := &file_rolodex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRblConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRblConfigResponse) ProtoMessage() {}

func (x *SetRblConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRblConfigResponse.ProtoReflect.Descriptor instead.
func (*SetRblConfigResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{11}
}

func (x *SetRblConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetRblConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetRblConfigRequest retrieves the current RBL configuration.
type GetRblConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRblConfigRequest) Reset() {
	*x = GetRblConfigRequest{}
	mi := &file_rolodex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRblConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRblConfigRequest) ProtoMessage() {}

func (x *GetRblConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRblConfigRequest.ProtoReflect.Descriptor instead.
func (*GetRblConfigRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{12}
}

func (x *GetRblConfigRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// GetRblConfigResponse contains the current RBL configuration.
type GetRblConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Providers     []*RblConfig           `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRblConfigResponse) Reset() {
	*x = GetRblConfigResponse{}
	mi := &file_rolodex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRblConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRblConfigResponse) ProtoMessage() {}

func (x *GetRblConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRblConfigResponse.ProtoReflect.Descriptor instead.
func (*GetRblConfigResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{13}
}

func (x *GetRblConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetRblConfigResponse) GetProviders() []*RblConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

// FlushCacheRequest clears the DNS and/or RBL cache.
type FlushCacheRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shared secret for authentication
	AuthToken     string `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushCacheRequest) Reset() {
	*x = FlushCacheRequest{}
	mi := &file_rolodex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheRequest) ProtoMessage() {}

func (x *FlushCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheRequest.ProtoReflect.Descriptor instead.
func (*FlushCacheRequest) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{14}
}

func (x *FlushCacheRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// FlushCacheResponse is returned after flushing the cache.
type FlushCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushCacheResponse) Reset() {
	*x = FlushCacheResponse{}
	mi := &file_rolodex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheResponse) ProtoMessage() {}

func (x *FlushCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rolodex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheResponse.ProtoReflect.Descriptor instead.
func (*FlushCacheResponse) Descriptor() ([]byte, []int) {
	return file_rolodex_proto_rawDescGZIP(), []int{15}
}

func (x *FlushCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlushCacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rolodex_proto protoreflect.FileDescriptor

const file_rolodex_proto_rawDesc = "" +
	"\n" +
	"\rrolodex.proto\x12\arolodex\"\x99\x01\n" +
	"\tDnsRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\vrecord_type\x18\x02 \x01(\x0e2\x13.rolodex.RecordTypeR\n" +
	"recordType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\"]\n" +
	"\x10AddRecordRequest\x12*\n" +
	"\x06record\x18\x01 \x01(\v2\x12.rolodex.DnsRecordR\x06record\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"G\n" +
	"\x11AddRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\x13RemoveRecordRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\vrecord_type\x18\x02 \x01(\x0e2\x13.rolodex.RecordTypeR\n" +
	"recordType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\"o\n" +
	"\x14RemoveRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rremoved_count\x18\x02 \x01(\rR\fremovedCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xbd\x01\n" +
	"\x12ListRecordsRequest\x12\x1f\n" +
	"\vname_filter\x18\x01 \x01(\tR\n" +
	"nameFilter\x12A\n" +
	"\x12record_type_filter\x18\x02 \x01(\x0e2\x13.rolodex.RecordTypeR\x10recordTypeFilter\x12$\n" +
	"\x0efilter_by_type\x18\x03 \x01(\bR\ffilterByType\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x04 \x01(\tR\tauthToken\"C\n" +
	"\x13ListRecordsResponse\x12,\n" +
	"\arecords\x18\x01 \x03(\v2\x12.rolodex.DnsRecordR\arecords\"T\n" +
	"\x13SetForwarderRequest\x12\x1e\n" +
	"\n" +
	"forwarders\x18\x01 \x03(\tR\n" +
	"forwarders\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"J\n" +
	"\x14SetForwarderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\tRblConfig\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x80\x01\n" +
	"\x13SetRblConfigRequest\x120\n" +
	"\tproviders\x18\x01 \x03(\v2\x12.rolodex.RblConfigR\tproviders\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"J\n" +
	"\x14SetRblConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13GetRblConfigRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"b\n" +
	"\x14GetRblConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x120\n" +
	"\tproviders\x18\x02 \x03(\v2\x12.rolodex.RblConfigR\tproviders\"2\n" +
	"\x11FlushCacheRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"H\n" +
	"\x12FlushCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\\\n" +
	"\n" +
	"RecordType\x12\x05\n" +
	"\x01A\x10\x00\x12\b\n" +
	"\x04AAAA\x10\x01\x12\t\n" +
	"\x05CNAME\x10\x02\x12\x06\n" +
	"\x02MX\x10\x03\x12\a\n" +
	"\x03TXT\x10\x04\x12\x06\n" +
	"\x02NS\x10\x05\x12\a\n" +
	"\x03SOA\x10\x06\x12\a\n" +
	"\x03SRV\x10\a\x12\a\n" +
	"\x03PTR\x10\b2\x9a\x04\n" +
	"\x0eRolodexService\x12B\n" +
	"\tAddRecord\x12\x19.rolodex.AddRecordRequest\x1a\x1a.rolodex.AddRecordResponse\x12K\n" +
	"\fRemoveRecord\x12\x1c.rolodex.RemoveRecordRequest\x1a\x1d.rolodex.RemoveRecordResponse\x12H\n" +
	"\vListRecords\x12\x1b.rolodex.ListRecordsRequest\x1a\x1c.rolodex.ListRecordsResponse\x12L\n" +
	"\rSetForwarders\x12\x1c.rolodex.SetForwarderRequest\x1a\x1d.rolodex.SetForwarderResponse\x12K\n" +
	"\fSetRblConfig\x12\x1c.rolodex.SetRblConfigRequest\x1a\x1d.rolodex.SetRblConfigResponse\x12K\n" +
	"\fGetRblConfig\x12\x1c.rolodex.GetRblConfigRequest\x1a\x1d.rolodex.GetRblConfigResponse\x12E\n" +
	"\n" +
	"FlushCache\x12\x1a.rolodex.FlushCacheRequest\x1a\x1b.rolodex.FlushCacheResponseb\x06proto3"

var (
	file_rolodex_proto_rawDescOnce sync.Once
	file_rolodex_proto_rawDescData []byte
)

func file_rolodex_proto_rawDescGZIP() []byte {
	file_rolodex_proto_rawDescOnce.Do(func() {
		file_rolodex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rolodex_proto_rawDesc), len(file_rolodex_proto_rawDesc)))
	})
	return file_rolodex_proto_rawDescData
}

var file_rolodex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rolodex_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rolodex_proto_goTypes = []any{
	(RecordType)(0),              // 0: rolodex.RecordType
	(*DnsRecord)(nil),            // 1: rolodex.DnsRecord
	(*AddRecordRequest)(nil),     // 2: rolodex.AddRecordRequest
	(*AddRecordResponse)(nil),    // 3: rolodex.AddRecordResponse
	(*RemoveRecordRequest)(nil),  // 4: rolodex.RemoveRecordRequest
	(*RemoveRecordResponse)(nil), // 5: rolodex.RemoveRecordResponse
	(*ListRecordsRequest)(nil),   // 6: rolodex.ListRecordsRequest
	(*ListRecordsResponse)(nil),  // 7: rolodex.ListRecordsResponse
	(*SetForwarderRequest)(nil),  // 8: rolodex.SetForwarderRequest
	(*SetForwarderResponse)(nil), // 9: rolodex.SetForwarderResponse
	(*RblConfig)(nil),            // 10: rolodex.RblConfig
	(*SetRblConfigRequest)(nil),  // 11: rolodex.SetRblConfigRequest
	(*SetRblConfigResponse)(nil), // 12: rolodex.SetRblConfigResponse
	(*GetRblConfigRequest)(nil),  // 13: rolodex.GetRblConfigRequest
	(*GetRblConfigResponse)(nil), // 14: rolodex.GetRblConfigResponse
	(*FlushCacheRequest)(nil),    // 15: rolodex.FlushCacheRequest
	(*FlushCacheResponse)(nil),   // 16: rolodex.FlushCacheResponse
}
var file_rolodex_proto_depIdxs = []int32{
	0,  // 0: rolodex.DnsRecord.record_type:type_name -> rolodex.RecordType
	1,  // 1: rolodex.AddRecordRequest.record:type_name -> rolodex.DnsRecord
	0,  // 2: rolodex.RemoveRecordRequest.record_type:type_name -> rolodex.RecordType
	0,  // 3: rolodex.ListRecordsRequest.record_type_filter:type_name -> rolodex.RecordType
	1,  // 4: rolodex.ListRecordsResponse.records:type_name -> rolodex.DnsRecord
	10, // 5: rolodex.SetRblConfigRequest.providers:type_name -> rolodex.RblConfig
	10, // 6: rolodex.GetRblConfigResponse.providers:type_name -> rolodex.RblConfig
	2,  // 7: rolodex.RolodexService.AddRecord:input_type -> rolodex.AddRecordRequest
	4,  // 8: rolodex.RolodexService.RemoveRecord:input_type -> rolodex.RemoveRecordRequest
	6,  // 9: rolodex.RolodexService.ListRecords:input_type -> rolodex.ListRecordsRequest
	8,  // 10: rolodex.RolodexService.SetForwarders:input_type -> rolodex.SetForwarderRequest
	11, // 11: rolodex.RolodexService.SetRblConfig:input_type -> rolodex.SetRblConfigRequest
	13, // 12: rolodex.RolodexService.GetRblConfig:input_type -> rolodex.GetRblConfigRequest
	15, // 13: rolodex.RolodexService.FlushCache:input_type -> rolodex.FlushCacheRequest
	3,  // 14: rolodex.RolodexService.AddRecord:output_type -> rolodex.AddRecordResponse
	5,  // 15: rolodex.RolodexService.RemoveRecord:output_type -> rolodex.RemoveRecordResponse
	7,  // 16: rolodex.RolodexService.ListRecords:output_type -> rolodex.ListRecordsResponse
	9,  // 17: rolodex.RolodexService.SetForwarders:output_type -> rolodex.SetForwarderResponse
	12, // 18: rolodex.RolodexService.SetRblConfig:output_type -> rolodex.SetRblConfigResponse
	14, // 19: rolodex.RolodexService.GetRblConfig:output_type -> rolodex.GetRblConfigResponse
	16, // 20: rolodex.RolodexService.FlushCache:output_type -> rolodex.FlushCacheResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rolodex_proto_init() }
func file_rolodex_proto_init() {
	if File_rolodex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rolodex_proto_rawDesc), len(file_rolodex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rolodex_proto_goTypes,
		DependencyIndexes: file_rolodex_proto_depIdxs,
		EnumInfos:         file_rolodex_proto_enumTypes,
		MessageInfos:      file_rolodex_proto_msgTypes,
	}.Build()
	File_rolodex_proto = out.File
	file_rolodex_proto_goTypes = nil
	file_rolodex_proto_depIdxs = nil
}
